# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Carp-DebugScreen
version:      0.09
version_from: lib/CGI/Carp/DebugScreen.pm
installdirs:  site
requires:
    CGI::Carp:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
